### ISSUE TITLE
Improve error reporting for 'autoinstall app create'

### ISSUE THREAD

**Issue by geoffswift** [salesforcecli/plugin-analytics#378]
**Is your feature request related to a problem? Please describe.**
I can't tell why app creation fails in a CI environment when using `sf analytics autoinstall app create`

**Describe the solution you'd like**
I would like to be able to see any errors explaining the root cause of app creation failure.

**Describe alternatives you've considered**
Manually testing the app creation.

**Additional context**
Here's an example of the output we get.  Any guesses what went wrong?
```
Waiting for auto-install request [0UZ8D00000010JnWAI] to finish... done
Error (1): Failure during Analytics app creation from auto-install request [0UZ8D00000010JnWAI]
```

**Comment by smithgp** [comment]
Hi @geoffswift, thanks for the feedback. In general, error info from autoinstalls ends up in the app log. It should be possible to get this as an option on the app create, to show the app log on error. I'll see about getting this scheduled.

In the mean time, some options are:
1. Run the create with `--json`, which will give json output that should include the last retrieved state of the auto install request, which I think should include the applog (although I haven't tried this in a bit so I'm not 100% sure). This is handy for scripting with the command since you can pipe it through a tool like `jq` to pull out discrete values.
2. After the failure you can run `sf analytic autoinstall display -a -i <the-id, e.g. 0UZ8D00000010JnWAI>`, which should include display app log.

Additionally, you can manually go to the Auto-Installed Apps setup page in the org in your browser; that should show the request and the logs, plus it should have a link to the App Install History, which will have even more details and logs (see details [here](https://developer.salesforce.com/docs/atlas.en-us.bi_dev_guide_wave_templates.meta/bi_dev_guide_wave_templates/bi_templatesdev_test_template_steps.htm)).

**Comment by smithgp** [comment]
@geoffswift - The next release (I think it'll be 1.4.10) will support a `--applog` option on `analytics autoinstall app create` and `update` that will print out the app log above the error or success message.
